apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: sync
        spec:
          restartPolicy: Never
          containers:
            - name: python
              image: "{{ .Values.werf.image.sync }}"
              workingDir: /app
              env:
                - name: MONGO_URI
                  value: "{{ .Values.mongodb.uri }}"
                - name: MONGO_DB_NAME
                  value: '{{ eq .Values.werf.env "staging" | ternary .Values.mongodb.dbName.staging .Values.mongodb.dbName._default }}'
                - name: TWITTER_AUTH_TOKEN
                  value: "{{ .Values.twitter.authToken }}"
                - name: REDIS_URI
                  value: "redis://{{ .Release.Name }}-redis-master"
                - name: DISABLE_SYNC
                  value: '{{ eq .Values.werf.env "staging" | ternary "True" "False" }}'
